---
title: "NHL API Vignette"
author: "John Clements"
date: "6/15/2021"
output: 
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Requirements

To use these functions, you need to install and load the [`jsonlite`](https://cran.r-project.org/web/packages/jsonlite/) and [`dplyr`](https://cran.r-project.org/web/packages/dplyr/) packages.

```{r message=FALSE, warning=FALSE}
# This library is useful for contacting an API.
library(jsonlite)
# This library is useful for manipulating dataframes.
library(dplyr)
```

# Functions

## `franchise`

```{r}
franchise <- function(team="all"){
  ###
  # This functions returns a dataframe with metadata on all teams who ever 
  # played in the NHL. It can also return those columns for a single team if a 
  # franchise ID or name is passed.
  ###
  
  # Get the franchise data from the franchises endpoint.
  outputAPI <- fromJSON(
      "https://records.nhl.com/site/api/franchise"
      )
  
  # Select only the dataframe.
  output <- outputAPI$data
  
  # If team does not equal "all", check if it is a franchise ID or team name.
  if (team != "all"){
    
    # If team is in the id column, subset output for just that row.
    if (team %in% output$id){
      output <- output %>%
        filter(id == team)
    }
    # If team is in the fullName column, subset output for just that row.
    else if (team %in% output$fullName){
      output <- output %>%
        filter(fullName == team)
    }
    # Otherwise, warn the user and return the entire dataframe.
    else {
      message <- paste("ERROR: Argument for team was not found in either",
                       "the fullName or id columns. Try franchise('all') to",
                       "find the team you're looking for.")
      stop(message)
    }
  }
  # Do nothing if the team value equals "all".
  else {
    
  }
  
  # Return the output dataframe.
  return(output)
}
```

## `teamTotals`

```{r}
teamTotals <- function(team="all"){
  ###
  # This function returns total stats for every franchise (ex roadTies,
  # roadWins, etc) unless a specific team Id or full team name is passed.
  ###
  
  # Get the franchise data from the franchises endpoint.
  outputAPI <- fromJSON(
    "https://records.nhl.com/site/api/franchise-team-totals"
    )
  
  # Select only the dataframe.
  output <- outputAPI$data
  
  # If team does not equal "all", check if it is a team ID or team name.
  if (team != "all"){
    
    # If team is in the franchiseId column, subset output for just that row.
    if (team %in% output$franchiseId){
      output <- output %>%
        filter(franchiseId == team)
    }
    # If team is in the teamName column, subset output for just that row.
    else if (team %in% output$teamName){
      output <- output %>%
        filter(teamName == team)
    }
    # Otherwise, warn the user and return the entire dataframe.
    else {
      message <- paste("WARNING: Argument for team was not found in either",
                       "the teamName or franchiseId columns. Returning all",
                       "franchises.")
      warning(message)
    }
  }
  # Do nothing if the team value equals "all".
  else {
    
  }
  
  # Return the output dataframe.
  return(output)
}
```

## `findFranchiseId`

This is a helper function to look up the most recent team id for a full team name e.g. "Boston Bruins" because I am too lazy to hard code it.

```{r}
findFranchiseId <- function(teamName){
  ###
  # This helper function looks up the franchise id for a full team name 
  # e.g. "Boston Bruins".
  ###
  
  # Call the franchise function with the team name.
  teamId <- franchise(teamName)
  
  # Return only the most recent team id number.
  return(teamId$mostRecentTeamId)
}
```


## `seasonRecords`

```{r}
seasonRecords <- function(team){
  ###
  # This functions returns a dataframe with the season records for a variety 
  # of stats for a single team.
  ###
  
  # If team is a "character" type, try to look up the team id.
  if (typeof(team) == "character"){
    teamId = findFranchiseId(team)
  }
  # If team is an integer, set teamId equal to team.
  else if ((typeof(team) == "double") & (team %% 1 == 0)){
    teamId = team
  }
  # Otherwise, throw an error.
  else {
    message <- paste("Please pass a team id (integer) or a full team name",
                     "e.g. 'Boston Bruins'.")
    stop(message)
  }
  
  # Set the base url, endpoint, and combine them with teamId for the full url.
  baseURL <- "https://records.nhl.com/site/api/"
  endpoint <- "franchise-season-records?cayenneExp=franchiseId="
  fullURL <- paste0(baseURL, endpoint, teamId)
  
  # Get the API output.
  outputAPI <- fromJSON(fullURL)
  # Select only the data.
  output <- outputAPI$data
  
  # Return the output from the request.
  return(output)
}
```

## `goalieRecords`

```{r}
goalieRecords <- function(team){
  ###
  # This functions returns a dataframe with the goalie records for a team.
  ###
  
  # If team is a "character" type, try to look up the team id.
  if (typeof(team) == "character"){
    teamId = findFranchiseId(team)
  }
  # If team is an integer, set teamId equal to team.
  else if ((typeof(team) == "double") & (team %% 1 == 0)){
    teamId = team
  }
  # Otherwise, throw an error.
  else {
    message <- paste("Please pass a team id (integer) or a full team name",
                     "e.g. 'Boston Bruins'.")
    stop(message)
  }
  
  # Set the base url, endpoint, and combine them with teamId for the full url.
  baseURL <- "https://records.nhl.com/site/api/"
  endpoint <- "franchise-goalie-records?cayenneExp=franchiseId="
  fullURL <- paste0(baseURL, endpoint, teamId)
  
  # Get the API output.
  outputAPI <- fromJSON(fullURL)
  # Select only the data.
  output <- outputAPI$data
  
  # Return the output from the request.
  return(output)
}
```

## `skaterRecords`

```{r}
skaterRecords <- function(team){
  ###
  # This functions returns a dataframe with the skater records for a team.
  ###
  
  # If team is a "character" type, try to look up the team id.
  if (typeof(team) == "character"){
    teamId = findFranchiseId(team)
  }
  # If team is an integer, set teamId equal to team.
  else if ((typeof(team) == "double") & (team %% 1 == 0)){
    teamId = team
  }
  # Otherwise, throw an error.
  else {
    message <- paste("Please pass a team id (integer) or a full team name",
                     "e.g. 'Boston Bruins'.")
    stop(message)
  }
  
  # Set the base url, endpoint, and combine them with teamId for the full url.
  baseURL <- "https://records.nhl.com/site/api/"
  endpoint <- "franchise-skater-records?cayenneExp=franchiseId="
  fullURL <- paste0(baseURL, endpoint, teamId)
  
  # Get the API output.
  outputAPI <- fromJSON(fullURL)
  # Select only the data.
  output <- outputAPI$data
  
  # Return the output from the request.
  return(output)
}
```

## `franchiseDetail`

```{r}
franchiseDetail <- function(team){
  ###
  # This functions returns a dataframe with the data for a team.
  ###
  
  # If team is a "character" type, try to look up the team id.
  if (typeof(team) == "character"){
    teamId = findFranchiseId(team)
  }
  # If team is an integer, set teamId equal to team.
  else if ((typeof(team) == "double") & (team %% 1 == 0)){
    teamId = team
  }
  # Otherwise, throw an error.
  else {
    message <- paste("Please pass a team id (integer) or a full team name",
                     "e.g. 'Boston Bruins'.")
    stop(message)
  }
  
  # Set the base url, endpoint, and combine them with teamId for the full url.
  baseURL <- "https://records.nhl.com/site/api/"
  endpoint <- "franchise-detail?cayenneExp=mostRecentTeamId="
  fullURL <- paste0(baseURL, endpoint, teamId)
  
  # Get the API output.
  outputAPI <- fromJSON(fullURL)
  # Select only the data.
  output <- outputAPI$data
  
  # Return the output from the request.
  return(output)
}
```










